// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package com.nvl.TestCaseAdapter.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_qmDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String QUALITY_MANAGEMENT_DOMAIN = "http://open-services.net/ns/qm#";
    public static String QUALITY_MANAGEMENT_NAMSPACE = "http://open-services.net/ns/qm#";
    public static String QUALITY_MANAGEMENT_NAMSPACE_PREFIX = "oslc_qm";

    public static String TESTCASE_PATH = "testCase";
    public static String TESTCASE_NAMESPACE = QUALITY_MANAGEMENT_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String TESTCASE_LOCALNAME = "TestCase"; //localName of the rdfs:class the resource describes
    public static String TESTCASE_TYPE = TESTCASE_NAMESPACE + TESTCASE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
