// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package com.nvl.TestCaseAdapter.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;

import org.eclipse.lyo.oslc4j.core.OSLC4JUtils;
import org.eclipse.lyo.oslc4j.core.exception.OslcCoreApplicationException;
import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRdfCollectionType;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;
import org.eclipse.lyo.oslc4j.core.model.ResourceShape;
import org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory;

import com.nvl.TestCaseAdapter.resources.Oslc_qmDomainConstants;


import com.nvl.TestCaseAdapter.resources.DctermsDomainConstants;
import com.nvl.TestCaseAdapter.resources.NvlQmDomainConstants;
import com.nvl.TestCaseAdapter.resources.FoafDomainConstants;
import com.nvl.TestCaseAdapter.resources.Oslc_qmDomainConstants;
import com.nvl.TestCaseAdapter.resources.RdfDomainConstants;


// Start of user code imports
// End of user code

// Start of user code preClassCode
// End of user code

// Start of user code classAnnotations
// End of user code
@OslcNamespace(Oslc_qmDomainConstants.TESTCASE_NAMESPACE)
@OslcName(Oslc_qmDomainConstants.TESTCASE_LOCALNAME)
@OslcResourceShape(title = "Descriptio", description = "Description (Test Case) defines the criteria which determine whether a system exhibits the correct behavior under a specific set of circumstances. ", describes = Oslc_qmDomainConstants.TESTCASE_TYPE)
public class TestCase
    extends AbstractResource
    implements ITestCase
{
    // Start of user code attributeAnnotation:identifier
    // End of user code
    private String identifier;
    // Start of user code attributeAnnotation:description
    // End of user code
    private String description;
    // Start of user code attributeAnnotation:created
    // End of user code
    private Date created;
    // Start of user code attributeAnnotation:dokumentenNummer
    // End of user code
    private String dokumentenNummer;
    // Start of user code attributeAnnotation:testLevel
    // End of user code
    private String testLevel;
    // Start of user code attributeAnnotation:createdby
    // End of user code
    private String createdby;
    // Start of user code attributeAnnotation:owner
    // End of user code
    private String owner;
    // Start of user code attributeAnnotation:title
    // End of user code
    private String title;
    // Start of user code attributeAnnotation:rdfObject
    // End of user code
    private Set<Link> rdfObject = new HashSet<Link>();
    
    // Start of user code classAttributes
    // End of user code
    // Start of user code classMethods
    // End of user code
    public TestCase()
    {
        super();
    
        // Start of user code constructor1
        // End of user code
    }
    
    public TestCase(final URI about)
    {
        super(about);
    
        // Start of user code constructor2
        // End of user code
    }
    
    public static ResourceShape createResourceShape() throws OslcCoreApplicationException, URISyntaxException {
        return ResourceShapeFactory.createResourceShape(OSLC4JUtils.getServletURI(),
        OslcConstants.PATH_RESOURCE_SHAPES,
        Oslc_qmDomainConstants.TESTCASE_PATH,
        TestCase.class);
    }
    
    
    public String toString()
    {
        return toString(false);
    }
    
    public String toString(boolean asLocalResource)
    {
        String result = "";
        // Start of user code toString_init
        // End of user code
    
        if (asLocalResource) {
            result = result + "{a Local TestCase Resource} - update TestCase.toString() to present resource as desired.";
            // Start of user code toString_bodyForLocalResource
            // End of user code
        }
        else {
            result = String.valueOf(getAbout());
        }
    
        // Start of user code toString_finalize
        // End of user code
    
        return result;
    }
    
    public void addRdfObject(final Link rdfObject)
    {
        this.rdfObject.add(rdfObject);
    }
    
    
    // Start of user code getterAnnotation:identifier
    // End of user code
    @OslcName("identifier")
    @OslcPropertyDefinition(DctermsDomainConstants.DUBLIN_CORE_NAMSPACE + "identifier")
    @OslcDescription("A unique identifier for a resource. Assigned by the service provider when a resource is created. Not intended for end-user display.")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("id")
    public String getIdentifier()
    {
        // Start of user code getterInit:identifier
        // End of user code
        return identifier;
    }
    
    // Start of user code getterAnnotation:description
    // End of user code
    @OslcName("description")
    @OslcPropertyDefinition(DctermsDomainConstants.DUBLIN_CORE_NAMSPACE + "description")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getDescription()
    {
        // Start of user code getterInit:description
        // End of user code
        return description;
    }
    
    // Start of user code getterAnnotation:created
    // End of user code
    @OslcName("created")
    @OslcPropertyDefinition(Oslc_qmDomainConstants.QUALITY_MANAGEMENT_NAMSPACE + "created")
    @OslcDescription("Timestamp of resource creation (reference: Dublin Core).")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    @OslcTitle("created")
    public Date getCreated()
    {
        // Start of user code getterInit:created
        // End of user code
        return created;
    }
    
    // Start of user code getterAnnotation:dokumentenNummer
    // End of user code
    @OslcName("dokumentenNummer")
    @OslcPropertyDefinition(NvlQmDomainConstants.NVL_QM_NAMSPACE + "dokumentenNummer")
    @OslcDescription("Entspricht der eindeutogen Dokumentennummer eines Dokuments aus dem PS-Systems.")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("docNumber")
    public String getDokumentenNummer()
    {
        // Start of user code getterInit:dokumentenNummer
        // End of user code
        return dokumentenNummer;
    }
    
    // Start of user code getterAnnotation:testLevel
    // End of user code
    @OslcName("testLevel")
    @OslcPropertyDefinition(NvlQmDomainConstants.NVL_QM_NAMSPACE + "testLevel")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcTitle("TestLevel")
    public String getTestLevel()
    {
        // Start of user code getterInit:testLevel
        // End of user code
        return testLevel;
    }
    
    // Start of user code getterAnnotation:createdby
    // End of user code
    @OslcName("createdby")
    @OslcPropertyDefinition(Oslc_qmDomainConstants.QUALITY_MANAGEMENT_NAMSPACE + "createdby")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcRange({FoafDomainConstants.PERSON_TYPE})
    @OslcReadOnly(false)
    public String getCreatedby()
    {
        // Start of user code getterInit:createdby
        // End of user code
        return createdby;
    }
    
    // Start of user code getterAnnotation:owner
    // End of user code
    @OslcName("owner")
    @OslcPropertyDefinition(Oslc_qmDomainConstants.QUALITY_MANAGEMENT_NAMSPACE + "owner")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcRange({FoafDomainConstants.PERSON_TYPE})
    @OslcReadOnly(false)
    public String getOwner()
    {
        // Start of user code getterInit:owner
        // End of user code
        return owner;
    }
    
    // Start of user code getterAnnotation:title
    // End of user code
    @OslcName("title")
    @OslcPropertyDefinition(DctermsDomainConstants.DUBLIN_CORE_NAMSPACE + "title")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getTitle()
    {
        // Start of user code getterInit:title
        // End of user code
        return title;
    }
    
    // Start of user code getterAnnotation:rdfObject
    // End of user code
    @OslcName("object")
    @OslcPropertyDefinition(RdfDomainConstants.RDF_NAMSPACE + "object")
    @OslcOccurs(Occurs.ZeroOrMany)
    @OslcValueType(ValueType.Resource)
    @OslcReadOnly(false)
    public Set<Link> getRdfObject()
    {
        // Start of user code getterInit:rdfObject
        // End of user code
        return rdfObject;
    }
    
    
    // Start of user code setterAnnotation:identifier
    // End of user code
    public void setIdentifier(final String identifier )
    {
        // Start of user code setterInit:identifier
        // End of user code
        this.identifier = identifier;
    
        // Start of user code setterFinalize:identifier
        // End of user code
    }
    
    // Start of user code setterAnnotation:description
    // End of user code
    public void setDescription(final String description )
    {
        // Start of user code setterInit:description
        // End of user code
        this.description = description;
    
        // Start of user code setterFinalize:description
        // End of user code
    }
    
    // Start of user code setterAnnotation:created
    // End of user code
    public void setCreated(final Date created )
    {
        // Start of user code setterInit:created
        // End of user code
        this.created = created;
    
        // Start of user code setterFinalize:created
        // End of user code
    }
    
    // Start of user code setterAnnotation:dokumentenNummer
    // End of user code
    public void setDokumentenNummer(final String dokumentenNummer )
    {
        // Start of user code setterInit:dokumentenNummer
        // End of user code
        this.dokumentenNummer = dokumentenNummer;
    
        // Start of user code setterFinalize:dokumentenNummer
        // End of user code
    }
    
    // Start of user code setterAnnotation:testLevel
    // End of user code
    public void setTestLevel(final String testLevel )
    {
        // Start of user code setterInit:testLevel
        // End of user code
        this.testLevel = testLevel;
    
        // Start of user code setterFinalize:testLevel
        // End of user code
    }
    
    // Start of user code setterAnnotation:createdby
    // End of user code
    public void setCreatedby(final String createdby )
    {
        // Start of user code setterInit:createdby
        // End of user code
        this.createdby = createdby;
    
        // Start of user code setterFinalize:createdby
        // End of user code
    }
    
    // Start of user code setterAnnotation:owner
    // End of user code
    public void setOwner(final String owner )
    {
        // Start of user code setterInit:owner
        // End of user code
        this.owner = owner;
    
        // Start of user code setterFinalize:owner
        // End of user code
    }
    
    // Start of user code setterAnnotation:title
    // End of user code
    public void setTitle(final String title )
    {
        // Start of user code setterInit:title
        // End of user code
        this.title = title;
    
        // Start of user code setterFinalize:title
        // End of user code
    }
    
    // Start of user code setterAnnotation:rdfObject
    // End of user code
    public void setRdfObject(final Set<Link> rdfObject )
    {
        // Start of user code setterInit:rdfObject
        // End of user code
        this.rdfObject.clear();
        if (rdfObject != null)
        {
            this.rdfObject.addAll(rdfObject);
        }
    
        // Start of user code setterFinalize:rdfObject
        // End of user code
    }
    
    
}
