// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

@OslcSchema ({
    @OslcNamespaceDefinition(prefix = OslcConstants.DCTERMS_NAMESPACE_PREFIX,             namespaceURI = OslcConstants.DCTERMS_NAMESPACE),
    @OslcNamespaceDefinition(prefix = OslcConstants.OSLC_CORE_NAMESPACE_PREFIX,           namespaceURI = OslcConstants.OSLC_CORE_NAMESPACE),
    @OslcNamespaceDefinition(prefix = OslcConstants.OSLC_DATA_NAMESPACE_PREFIX,           namespaceURI = OslcConstants.OSLC_DATA_NAMESPACE),
    @OslcNamespaceDefinition(prefix = OslcConstants.RDF_NAMESPACE_PREFIX,                 namespaceURI = OslcConstants.RDF_NAMESPACE),
    @OslcNamespaceDefinition(prefix = OslcConstants.RDFS_NAMESPACE_PREFIX,                namespaceURI = OslcConstants.RDFS_NAMESPACE),
    @OslcNamespaceDefinition(prefix = DctermsDomainConstants.DUBLIN_CORE_NAMSPACE_PREFIX, namespaceURI = DctermsDomainConstants.DUBLIN_CORE_NAMSPACE),
    @OslcNamespaceDefinition(prefix = NvlQmDomainConstants.NVL_QM_NAMSPACE_PREFIX, namespaceURI = NvlQmDomainConstants.NVL_QM_NAMSPACE),
    @OslcNamespaceDefinition(prefix = Oslc_qmDomainConstants.OSLC_QM_NAMSPACE_PREFIX, namespaceURI = Oslc_qmDomainConstants.OSLC_QM_NAMSPACE),
    @OslcNamespaceDefinition(prefix = RdfDomainConstants.RDF_NAMSPACE_PREFIX, namespaceURI = RdfDomainConstants.RDF_NAMSPACE)
})
package com.nvl.TestCaseAdapter.resources;

import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespaceDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcSchema;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

import com.nvl.TestCaseAdapter.resources.DctermsDomainConstants;
import com.nvl.TestCaseAdapter.resources.NvlQmDomainConstants;
import com.nvl.TestCaseAdapter.resources.Oslc_qmDomainConstants;
import com.nvl.TestCaseAdapter.resources.RdfDomainConstants;

